name: Notion Dedupe

on:
  schedule:
    - cron: "*/15 * * * *"   # every 5 min (UTC)
  workflow_dispatch:

concurrency:
  group: notion-dedupe
  cancel-in-progress: false

jobs:
  dedupe:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # No cache to avoid "Dependencies lock file not found" error
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install @notionhq/client
        run: |
          if [ ! -f package.json ]; then
            npm init -y >/dev/null 2>&1
          fi
          npm i @notionhq/client --no-audit --no-fund

      - name: Run dedupe
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          UID_PROP: uid
          PRIMARY_PROP: Primary
          LAST_DEDUPE_PROP: "Last deduped"
          # AUTO_ARCHIVE: "1"
          # ARCHIVE_STATUS_NAME: Archived
        run: node ops/dedupe.mjs
