name: Notion Dedupe

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 min (UTC)
  workflow_dispatch:

concurrency:
  group: notion-dedupe
  cancel-in-progress: false

jobs:
  dedupe:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install deps (ephemeral). If your repo has a lockfile, we'll use npm ci.
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --no-audit --no-fund
          else
            npm init -y >/dev/null 2>&1 || true
            npm i @notionhq/client --no-audit --no-fund
          fi

      - name: Run dedupe
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          UID_PROP: uid
          PRIMARY_PROP: Primary
          LAST_DEDUPE_PROP: Last deduped
          # Set to "1" if you want older rows auto-archived and you have a "Status" select
          # AUTO_ARCHIVE: "1"
          # ARCHIVE_STATUS_NAME: Archived
        run: node ops/dedupe.mjs
